from django.urls import path

from .views import (
    DeleteExpenseView,
    MarkExpenseView,
    SpeakerExpenseDetail,
    SpeakerExpenseList,
    SpeakerList,
    SpeakerTourManagement,
    TourListView,
    TourDetailView,
    TourDeleteView,
    ShuttleView,
    ShuttleExportSettingsView,
    AccommodationListView,
    AccommodationDetailView,
    AccommodationDeleteView,
    AccommodationBookingCreateView,
    AccommodationBookingDeleteView,
)

urlpatterns = [
    path(
        "orga/event/<slug:event>/settings/plugins/hitalx/shuttle-export/",
        view=ShuttleExportSettingsView.as_view(),
        name="tours.export.settings",
    ),
    path(
        "orga/event/<slug:event>/speakers-by-expense/",
        view=SpeakerList.as_view(),
        name="speakers_by_expense.view",
    ),
    path(
        "orga/event/<slug:event>/speakers/<int:pk>/tours/",
        view=SpeakerTourManagement.as_view(),
        name="speaker_tours.view",
    ),
    path(
        "orga/event/<slug:event>/tours/",
        view=TourListView.as_view(),
        name="tours.view",
    ),
    path(
        "orga/event/<slug:event>/tours/<int:pk>",
        view=TourDetailView.as_view(),
        name="tour.view",
    ),
    path(
        "orga/event/<slug:event>/tours/<int:pk>/delete",
        view=TourDeleteView.as_view(),
        name="tour.delete",
    ),
    path(
        "orga/event/<slug:event>/tours/export",
        view=ShuttleView.as_view(),
        name="tours.export",
    ),
    path(
        "orga/event/<slug:event>/tours/new",
        view=TourDetailView.as_view(),
        name="tour.create",
    ),
    path(
        "orga/event/<slug:event>/speakers/<int:speaker_id>/expenses/",
        view=SpeakerExpenseList.as_view(),
        name="expenses.view",
    ),
    path(
        "orga/event/<slug:event>/speakers/<int:speaker_id>/expenses/new",
        view=SpeakerExpenseDetail.as_view(),
        name="expenses.create",
    ),
    path(
        "orga/event/<slug:event>/speakers/<int:speaker_id>/expense/<int:pk>",
        view=SpeakerExpenseDetail.as_view(),
        name="expense.view",
    ),
    path(
        "orga/event/<slug:event>/speakers/<int:speaker_id>/expense/<int:pk>/mark",
        view=MarkExpenseView.as_view(),
        name="expense.mark",
    ),
    path(
        "orga/event/<slug:event>/speakers/<int:speaker_id>/expense/<int:pk>/delete",
        view=DeleteExpenseView.as_view(),
        name="expense.delete",
    ),
    # Accommodations
    path(
        "orga/event/<slug:event>/accommodations/",
        view=AccommodationListView.as_view(),
        name="accommodations.view",
    ),
    path(
        "orga/event/<slug:event>/accommodations/new",
        view=AccommodationDetailView.as_view(),
        name="accommodation.create",
    ),
    path(
        "orga/event/<slug:event>/accommodations/<int:pk>/",
        view=AccommodationDetailView.as_view(),
        name="accommodation.view",
    ),
    path(
        "orga/event/<slug:event>/accommodations/<int:pk>/delete",
        view=AccommodationDeleteView.as_view(),
        name="accommodation.delete",
    ),
    path(
        "orga/event/<slug:event>/accommodations/<int:pk>/booking/new",
        view=AccommodationBookingCreateView.as_view(),
        name="accommodation.booking.create",
    ),
    path(
        "orga/event/<slug:event>/accommodation-booking/<int:pk>/delete",
        view=AccommodationBookingDeleteView.as_view(),
        name="accommodation.booking.delete",
    ),
]
