from django.urls import path, include
from pretalx.event.models.event import SLUG_REGEX

from .views import (
    MarkExpenseView,
    SpeakerExpenseDetail,
    SpeakerExpenseList,
    SpeakerList,
    SpeakerTourManagement,
    TourListView,
    TourDetailView,
    TourDeleteView,
    ShuttleView,
)

app_name = "pretalx_hitalx"
urlpatterns = [
    path(
        "orga/event/<slug:event>/p/hitalx/",
        include(
            [
                path(
                    "speakers/",
                    SpeakerList.as_view(),
                    name="speakers_by_expense.view",
                ),
                path(
                    "speakers/<int:pk>/tours/",
                    SpeakerTourManagement.as_view(),
                    name="speaker_tours.view",
                ),
                path(
                    "tours/",
                    TourListView.as_view(),
                    name="tours.view",
                ),
                path(
                    "tours/new",
                    TourDetailView.as_view(),
                    name="tour.create",
                ),
                path(
                    "tours/<int:pk>/",
                    TourDetailView.as_view(),
                    name="tour.view",
                ),
                path(
                    "tours/<int:pk>/delete",
                    TourDeleteView.as_view(),
                    name="tour.delete",
                ),
                path(
                    "tours/export",
                    ShuttleView.as_view(),
                    name="tours.export",
                ),
                path(
                    "speakers/<int:speaker_id>/expenses/",
                    SpeakerExpenseList.as_view(),
                    name="expenses.view",
                ),
                path(
                    "speakers/<int:speaker_id>/expenses/new",
                    SpeakerExpenseDetail.as_view(),
                    name="expenses.create",
                ),
                path(
                    "speakers/<int:speaker_id>/expenses/<int:pk>/",
                    SpeakerExpenseDetail.as_view(),
                    name="expense.view",
                ),
                path(
                    "speakers/<int:speaker_id>/expenses/<int:pk>/mark",
                    MarkExpenseView.as_view(),
                    name="expense.mark",
                ),
            ]
        ),
    ),
]
